export const simpleMockChangeRequests = [
  {
    id: 'CR-2024-001',
    changeType: 'CREATE',
    entityType: 'COUNTRY',
    entityId: '',
    description: 'Add South Sudan as a new country',
    requestedBy: 'john.smith@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'PENDING',
    newValues: { countryCode: 'SS', countryName: 'South Sudan' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'CR-2024-002',
    changeType: 'UPDATE',
    entityType: 'PORT',
    entityId: 'port-001',
    description: 'Update Port of Los Angeles capabilities',
    requestedBy: 'jane.doe@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'APPROVED',
    oldValues: { capabilities: ['CONTAINER', 'BULK_CARGO'] },
    newValues: { capabilities: ['CONTAINER', 'BULK_CARGO', 'LNG', 'CRUISE'] },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-003',
    changeType: 'UPDATE',
    entityType: 'AIRPORT',
    entityId: 'airport-002',
    description: 'Update JFK Airport terminal count',
    requestedBy: 'bob.johnson@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'APPROVED',
    oldValues: { terminalCount: 6 },
    newValues: { terminalCount: 8 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-004',
    changeType: 'DELETE',
    entityType: 'COUNTRY',
    entityId: 'country-004',
    description: 'Deactivate obsolete country code',
    requestedBy: 'alice.wilson@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'REJECTED',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-005',
    changeType: 'CREATE',
    entityType: 'PORT',
    entityId: '',
    description: 'Add new inland port in Kansas City',
    requestedBy: 'mike.brown@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'PENDING',
    newValues: { portCode: 'USKCI', portName: 'Kansas City Inland Port' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-006',
    changeType: 'UPDATE',
    entityType: 'COUNTRY',
    entityId: 'country-006',
    description: 'Update Turkey official name to Türkiye',
    requestedBy: 'sarah.martinez@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'PENDING',
    oldValues: { countryName: 'Turkey' },
    newValues: { countryName: 'Türkiye' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-007',
    changeType: 'CREATE',
    entityType: 'AIRPORT',
    entityId: '',
    description: 'Add new regional airport in Nashville',
    requestedBy: 'david.lee@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'PENDING',
    newValues: { airportCode: 'BNA', airportName: 'Nashville International Airport' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-008',
    changeType: 'UPDATE',
    entityType: 'PORT',
    entityId: 'port-008',
    description: 'Update Port of Miami cargo capacity',
    requestedBy: 'emily.chen@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'APPROVED',
    oldValues: { cargoCapacity: '1.2M TEU' },
    newValues: { cargoCapacity: '1.5M TEU' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-009',
    changeType: 'DELETE',
    entityType: 'AIRPORT',
    entityId: 'airport-009',
    description: 'Remove closed military airfield',
    requestedBy: 'robert.taylor@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'CANCELLED',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-010',
    changeType: 'CREATE',
    entityType: 'COUNTRY',
    entityId: '',
    description: 'Add Kosovo as recognized country',
    requestedBy: 'maria.garcia@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'PENDING',
    newValues: { countryCode: 'XK', countryName: 'Kosovo' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-011',
    changeType: 'UPDATE',
    entityType: 'PORT',
    entityId: 'port-011',
    description: 'Update Port of Seattle operating hours',
    requestedBy: 'james.anderson@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'APPROVED',
    oldValues: { operatingHours: '6AM-10PM' },
    newValues: { operatingHours: '24/7' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-012',
    changeType: 'UPDATE',
    entityType: 'AIRPORT',
    entityId: 'airport-012',
    description: 'Update LAX runway configuration',
    requestedBy: 'patricia.white@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'PENDING',
    oldValues: { runways: 4 },
    newValues: { runways: 5 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-013',
    changeType: 'CREATE',
    entityType: 'PORT',
    entityId: '',
    description: 'Add new cruise terminal in Charleston',
    requestedBy: 'thomas.moore@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'PENDING',
    newValues: { portCode: 'USCHS', portName: 'Charleston Cruise Terminal' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-014',
    changeType: 'UPDATE',
    entityType: 'COUNTRY',
    entityId: 'country-014',
    description: 'Update Czech Republic to Czechia',
    requestedBy: 'jennifer.davis@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'APPROVED',
    oldValues: { countryName: 'Czech Republic' },
    newValues: { countryName: 'Czechia' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-015',
    changeType: 'DELETE',
    entityType: 'PORT',
    entityId: 'port-015',
    description: 'Remove decommissioned naval port',
    requestedBy: 'michael.clark@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'REJECTED',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-016',
    changeType: 'CREATE',
    entityType: 'AIRPORT',
    entityId: '',
    description: 'Add new cargo hub in Louisville',
    requestedBy: 'lisa.rodriguez@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'PENDING',
    newValues: { airportCode: 'SDF', airportName: 'Louisville International Airport' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-017',
    changeType: 'UPDATE',
    entityType: 'PORT',
    entityId: 'port-017',
    description: 'Update Houston port security level',
    requestedBy: 'daniel.walker@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'PENDING',
    oldValues: { securityLevel: 'MARSEC 1' },
    newValues: { securityLevel: 'MARSEC 2' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-018',
    changeType: 'UPDATE',
    entityType: 'AIRPORT',
    entityId: 'airport-018',
    description: 'Update Denver airport elevation data',
    requestedBy: 'nancy.hall@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'APPROVED',
    oldValues: { elevation: '5430 ft' },
    newValues: { elevation: '5434 ft' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-019',
    changeType: 'CREATE',
    entityType: 'COUNTRY',
    entityId: '',
    description: 'Add Northern Cyprus entity',
    requestedBy: 'christopher.lopez@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'REJECTED',
    newValues: { countryCode: 'CY-NC', countryName: 'Northern Cyprus' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'CR-2024-020',
    changeType: 'UPDATE',
    entityType: 'PORT',
    entityId: 'port-020',
    description: 'Update Baltimore port rail connections',
    requestedBy: 'amanda.martinez@cbp.gov',
    requestedAt: new Date().toISOString(),
    status: 'PENDING',
    oldValues: { railConnections: 2 },
    newValues: { railConnections: 3 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];