FROM docker.cbp.dhs.gov/cloud/ubi/nodejs-build:22 AS builder
WORKDIR /app
COPY package*.json ./
ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN npm install
COPY . .
RUN npm run build

FROM docker.cbp.dhs.gov/cloud/ubi/nginx:1.26

# Install 'gettext' which provides the 'envsubst' utility
RUN dnf install -y gettext && dnf clean all

COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy and make the entrypoint script executable
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]