spring:
  application:
    name: reference-data-service
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/reference_data
    username: refdata_user
    password: ${DB_PASSWORD:refdata_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # Kafka configuration (disabled for minimal setup)
  # kafka:
  #   bootstrap-servers: kafka:29092
  
  # Redis configuration
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
  
  # Security configuration (disabled for minimal setup)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: none

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    gov.dhs.cbp.reference: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application specific configuration
reference-data:
  outbox:
    polling-interval: 5000
    batch-size: 100
  loaders:
    enabled: true
    schedule:
      iso-countries: "0 2 * * *"  # Daily at 2 AM
      genc-countries: "0 3 * * *" # Daily at 3 AM
      iata-airports: "0 4 * * *"  # Daily at 4 AM
      icao-airports: "0 5 * * *"  # Daily at 5 AM
      cbp-ports: "0 6 * * *"      # Daily at 6 AM