# H2 Database Configuration for Local Development
# Usage: ./mvnw spring-boot:run -Dspring-boot.run.profiles=h2

spring:
  datasource:
    url: jdbc:h2:mem:refdata;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;INIT=CREATE SCHEMA IF NOT EXISTS reference_data
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate  # Only validate schema, don't create/drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_schema: reference_data
    show-sql: true  # Show SQL queries in console for debugging

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false  # Only allow localhost access

  liquibase:
    enabled: true  # Enable Liquibase to create tables
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: reference_data
    liquibase-schema: reference_data

  # Disable Kafka for local H2 development
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        enable.idempotence: false
    consumer:
      properties:
        enable.auto.commit: false

  # Security configuration
  security:
    enabled: false  # Disable security for easier local development

# Simplified logging for H2 development
logging:
  level:
    gov.dhs.cbp.reference: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.h2: DEBUG
    liquibase: INFO

# Server configuration
server:
  port: 8082  # Different port to avoid conflicts with Docker