spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  sql:
    init:
      schema-locations: classpath:schema-h2-no-schema.sql
      mode: always
      separator: ;
      
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  
  liquibase:
    enabled: false
  
  test:
    database:
      replace: none

  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://test.okta.com
          jwk-set-uri: https://test.okta.com/oauth2/default/v1/keys

# Test logging configuration
logging:
  level:
    gov.dhs.cbp.reference: DEBUG
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.hibernate.SQL: INFO
    org.h2.server: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

# API Configuration
api:
  cors:
    allowed-origins: http://localhost:4200,http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    exposed-headers: ETag,X-Total-Count
    allow-credentials: true

# Server configuration for tests
server:
  error:
    include-message: always
    include-binding-errors: always